setup: |
  echo "🐊 All project dependencies have been installed!"
---

# perform checks on a file
- writing/VSCode_command.md:
    - description: Ensure that a VSCode_command.md files exist
      check: ConfirmFileExists
    - description: No TODOs remain in the VSCode_command.md files
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true

- writing/lab3.py:
    - description: Ensure that a lab3.py file exists
      check: ConfirmFileExists
    - description: Check that the print statement exists in the lab3.py file
      check: MatchFileFragment
      options:
        fragment: 'print ("Hello, VSCode!")'
        count: 1
        exact: false

- writing/debug.py:
    - description: Ensure that a debug.py file exists
      check: ConfirmFileExists
    - description: Check that the print statement exists in the debug.py file
      check: MatchFileFragment
      options:
        fragment: 'elif religion in non_christian_religions:'
        count: 1
        exact: true

- writing/debug.png:
    - description: Ensure that a debug.png screenshot file exists
      check: ConfirmFileExists

- writing/reflection.md:
    - description: Ensure that the reflection.md files exist
      check: ConfirmFileExists
    - description: No TODOs remain in the reflection.md files
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Write a minimum number of meaningful words (200) in the reflection.md
      check: CountFileWords
      options:
        count: 200
        exact: false

# count number of commits in the GitHub repository
- description: Have at least 3 of commits in repository
  check: CountCommits
  options:
    count: 3
